import itertools
from os import path

from snakemake.utils import min_version

min_version("7.19.1")  # this is where SLURM support was introduced


LOCAL_INPUT = config["LOCAL_INPUT_DIR"]
DATABASE = config["DATABASE"]
SUBSET = config["SUBSET"]
RESCREENING_TARGETS = config["RESCREENING_TARGETS"]


def generateOutput(wildcards):
    irods = path.join("results", "irods.json")
    if config["RESCREENING"] == "TRUE":
        out = expand(
            path.join(
                "results",
                "rescreening_{percentage}",
                "{receptorID}",
                "union.csv",
            ),
            receptorID=config["TARGETS"][0].split(",")[0],
            percentage=config["RESULT_NUMBER"],
            combAll=combAll,
        )
        hist = expand(
            path.join("results", "{receptorID}_hist.png"),
            receptorID=config["TARGETS"][0].split(",")[0],
        )
        return hist + out + [irods]
    else:
        out = expand(
            path.join("results", "{receptorID}_{percentage}.csv"),
            receptorID=config["TARGETS"][0].split(",")[0],
            percentage=config["RESULT_NUMBER"],
        )
        hist = expand(
            path.join("results", "{receptorID}_hist.png"),
            receptorID=config["TARGETS"][0].split(",")[0],
        )
        return hist + out + [irods]

targetList = []  # get ProteinIDs from configfile for rescreening
for i in config["RESCREENING_TARGETS"]:
    targetList.append(i.split(",")[0])

combList = []
for comb in itertools.combinations(targetList, 2):  # all combinations of two targets

    combList.append("_".join(comb))

combAll = "_".join(targetList)  # combine all rescreening targets


def getAllVenn(wildcards):
    path.join(
        "output",
        "rescreening",
        "{receptorID}",
        "{RESCREENING_TARGETS}_union.txt",
    )


def IRODSinput(wildcards):
    if config["RESCREENING"] == "TRUE":
        out = expand(
            path.join(
                "results",
                "rescreening_{percentage}",
                "{receptorID}",
                "union.csv",
            ),
            receptorID=config["TARGETS"][0].split(",")[0],
            percentage=config["RESULT_NUMBER"],
            combAll=combAll,
        )
    else:
        out = expand(
            path.join("results", "{receptorID}_{percentage}.csv"),
            receptorID=config["TARGETS"][0].split(",")[0],
            percentage=config["RESULT_NUMBER"],
        )
    return out


def resources(RULE_NAME):
    out_list = []
    for key in config[RULE_NAME]:
        out_list.append(f"{key} = {config[RULE_NAME][key]}")
    out_str = ",\n".join(out_list)
    return out_str


rule all:
    input:
        generateOutput,


rule generateIRODS:
    input:
        IRODSinput,
    output:
        path.join("results", "irods.json"),
    log:
        "logs/generateIRODS.log",
    script:
        "scripts/generateIRODS.py"


include: "rules/preparation.smk"
include: "rules/docking.smk"
include: "rules/analyse.smk"

